import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";

describe("formal console contract", () => {
  it("contains all nine settings/data/about pages and no debug shortcut", async () => {
    const source = await readFile(new URL("../src/console/main.ts", import.meta.url), "utf8");
    for (const page of ["总览", "外观与桌宠", "状态与动作", "感知与隐私", "提醒与陪伴", "智能体 API", "数据统计", "数据与存储", "关于与更新"]) expect(source).toContain(page);
    expect(source).not.toContain("Ctrl+Shift+D");
    expect(source).toContain("24 个正式动作");
    expect(source).not.toContain("导出 CSV");
    expect(source).not.toContain("导出 JSON");
    expect(source).not.toContain("data-export");
    expect(source).toContain("buttonLabel('refresh','刷新')");
    expect(source).toContain("关于与更新");
    expect(source).toContain('data-command="check-update"');
    expect(source).toContain('data-command="download-update"');
    expect(source).toContain('data-command="install-update"');
    expect(source).toContain('data-command="open-release-page"');
    expect(source).toContain('data-command="show-onboarding"');
    expect(source).toContain('data-command="onboarding-private"');
    expect(source).toContain('data-command="onboarding-enable"');
    expect(source).toContain('data-command="onboarding-open-ai"');
    expect(source).toContain("DeepSeek API Key");
    expect(source).toContain('${this.petName()}桌宠 · 正式发布通道');
    expect(source).toContain('<h3>关于${this.petName()}桌宠</h3>');
    expect(source).not.toContain('珊珊桌宠 · 正式发布通道');
    expect(source).not.toContain('<h3>关于珊珊桌宠</h3>');
    expect(source).toContain("珊珊桌宠版权声明");
    expect(source).toContain("开发者浩涵设计、开发并持续发布");
    expect(source).toContain("© 2026 浩涵");
    expect(source).toContain("第三方开源组件仍分别遵循其各自许可证");
    expect(source).toContain('private syncUpdatePanel():void');
    expect(source).not.toContain("if(phaseChanged)this.render(true)");
    expect(source).not.toContain("updates.check();this.render(true)");
    expect(source).not.toContain("新用户首次安装默认目录");
    expect(source).not.toContain("当前测试安装包尚未配置 Windows 代码签名");
    expect(source).not.toContain("测试包暂未签名");
    expect(source).toContain("data-base-url readonly");
    expect(source).toContain("edit-base-url");
    expect(source).toContain("save-base-url");
    expect(source).toContain("重新查看首次使用指引");
    expect(source).toContain("选择新的存储文件夹");
    expect(source).toContain("实时感知诊断");
    expect(source).toContain("当前资源消耗");
    expect(source).toContain("data-stats-range");
    expect(source).not.toContain("statsRefreshAt");
    expect(source).toContain("previousScroll");
    const styles = await readFile(new URL("../src/console/styles.css", import.meta.url), "utf8");
    expect(styles).toContain("height: 100vh");
    expect(styles).toContain("overflow-y: auto");
    expect(source).toContain('time-picker');
    expect(source).toContain('class="custom-select"');
    expect(source).not.toContain('type="time"');
    expect(source).not.toContain('<select');
    expect(source).toContain('role="switch"');
    expect(source).toContain('AI 智能问候文案');
    expect(source).toContain('smartCompanionSpeech');
    expect(source).toContain('syncAppearanceScale');
    expect(source).toContain('return `${Math.max(0,Math.ceil((this.settings.manualUntil-Date.now())/1000))} 秒后恢复自动`;');
    expect(source).not.toContain('剩余 ${Math.max(0,Math.ceil((this.settings.manualUntil-Date.now())/1000))} 秒后恢复自动');
    expect(source).toContain('气泡与文字大小');
    expect(source).not.toContain('this.range("气泡字号"');
    const settingsSource = await readFile(new URL("../electron/services/SettingsStore.ts", import.meta.url), "utf8");
    expect(settingsSource).toContain('smartCompanionSpeech: true');
    expect(source).not.toContain('["sleep","睡眠"]');
    expect(styles).toContain("::-webkit-slider-thumb");
    expect(styles).toContain("scrollbar-gutter: auto");
    expect(styles).not.toContain(".performance-note { display: none");
    expect(styles).toContain(".tour-mask");
    expect(styles).toContain(".tour-card button.tour-primary");
    const chatStyles = await readFile(new URL("../src/chat/styles.css", import.meta.url), "utf8");
    const petStyles = await readFile(new URL("../src/styles.css", import.meta.url), "utf8");
    expect(styles).toContain("--danger: color-mix(in srgb, var(--accent)");
    expect(chatStyles).toContain("--danger: color-mix(in srgb, var(--accent)");
    expect(petStyles).toContain("background: color-mix(in srgb,var(--accent) 14%,transparent)");
  });
});
